name = "LeanSage"
version = "0.1.0"
defaultTargets = ["LeanSage"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.22.0"

[[lean_lib]]
name = "LeanSage"

[[lean_exe]]
name = "leansage"
root = "Main"
